<p align="center">

<picture>

<source media="(prefers-color-scheme: dark)"
srcset="https://raw.githubusercontent.com/tarunsakhamuri-917/tarunsakhamuri-917/output/github-snake-dark.svg"/>

<source media="(prefers-color-scheme: light)"
srcset="https://raw.githubusercontent.com/tarunsakhamuri-917/tarunsakhamuri-917/output/github-snake.svg"/>

<img alt="GitHub Contribution Snake"
src="https://raw.githubusercontent.com/tarunsakhamuri-917/tarunsakhamuri-917/output/github-snake.svg"/>

</picture>

</p>
